-- Church Prayer Live v1.1
-- Supabase SQL Editor에서 1회 실행

create table if not exists public.prayers (
  id bigint generated by default as identity primary key,
  name varchar(30) not null default '익명',
  text varchar(300) not null,
  created_at timestamptz not null default now()
);

create index if not exists prayers_created_at_idx
  on public.prayers (created_at desc);

alter table public.prayers enable row level security;

-- 현재 v1.1에서는 브라우저가 Supabase에 직접 접근하지 않습니다.
-- Render 서버가 SERVICE_ROLE_KEY로만 DB에 접근하므로
-- anon/authenticated 대상 RLS 정책은 만들지 않습니다.
